import type {
  ApplicationRecord,
  DocumentRecord,
  FamilyProfile,
  NotificationRecord,
  Scholarship,
  StudentProfile,
} from "@/lib/app-types"

export const baseDocuments: DocumentRecord[] = [
  { id: "doc-aadhaar", name: "Aadhaar Identity", type: "Identity", verified: true },
  { id: "doc-community", name: "ST Community Certificate", type: "Community", verified: true },
  { id: "doc-income", name: "Income Certificate", type: "Income", verified: true },
  { id: "doc-domicile", name: "Domicile Certificate", type: "Residence", verified: true },
  { id: "doc-marksheet", name: "Academic Marksheet", type: "Academic", verified: true },
  { id: "doc-bonafide", name: "Bonafide Certificate", type: "Institution", verified: true },
  { id: "doc-disability", name: "Disability Certificate", type: "Optional", verified: false, optional: true },
]

export const students: StudentProfile[] = [
  {
    id: "student-arun",
    name: "Arun Kumar",
    phone: "98765 43210",
    category: "ST",
    dateOfBirth: "15/08/2006",
    state: "Tamil Nadu",
    annualIncome: 180000,
    institution: "ABC Engineering College",
    course: "B.E Computer Science",
    year: "2nd Year",
    educationLevel: "undergraduate",
    academicScore: 84,
    topInstitution: true,
    netJrf: false,
    overseasIntent: false,
    documents: baseDocuments,
  },
  {
    id: "student-priya",
    name: "Priya Kumar",
    phone: "98123 45067",
    category: "ST",
    dateOfBirth: "04/03/2012",
    state: "Tamil Nadu",
    annualIncome: 125000,
    institution: "Government Tribal Residential School",
    course: "Class 9",
    year: "Class 9",
    educationLevel: "school",
    academicScore: 88,
    topInstitution: false,
    netJrf: false,
    overseasIntent: false,
    classLevel: 9,
    documents: baseDocuments.slice(0, 5),
  },
  {
    id: "student-meena",
    name: "Meena Devi",
    phone: "98987 65012",
    category: "ST",
    dateOfBirth: "21/11/1999",
    state: "Jharkhand",
    annualIncome: 220000,
    institution: "Central University of Jharkhand",
    course: "Ph.D. Sociology",
    year: "Research Year 1",
    educationLevel: "research",
    academicScore: 79,
    topInstitution: true,
    netJrf: true,
    overseasIntent: false,
    documents: baseDocuments,
  },
]

export const scholarships: Scholarship[] = [
  {
    id: "pre-matric",
    shortName: "Pre-Matric",
    name: "Pre-Matric Scholarship for ST Students",
    description: "Financial assistance for ST students studying in school (Classes 9th and 10th) to reduce drop-out rates.",
    benefit: "Up to ₹12,000 per year + allowances",
    deadline: "30 September 2026",
    timeline: "June 1 – September 30",
    category: "ST",
    targetClass: "9th or 10th",
    incomeLimit: "₹2.5 Lakh / year",
    priority: 2,
    criteria: [
      "Category: ST (Scheduled Tribe)",
      "Class: 9th or 10th standard",
      "Family Income: Up to ₹2.5 Lakh per annum",
      "Application Window: June 1 – September 30",
    ],
    requiredDocuments: ["Aadhaar Identity", "ST Community Certificate", "Income Certificate", "Academic Marksheet"],
  },
  {
    id: "post-matric",
    shortName: "Post-Matric",
    name: "Post-Matric Scholarship for ST Students",
    description: "Support for ST students pursuing Class 11th, 12th, and post-secondary / higher education degrees.",
    benefit: "Up to ₹48,000 per year + maintenance allowance",
    deadline: "31 October 2026",
    timeline: "June 1 – October 31",
    category: "ST",
    targetClass: "11th, 12th & Higher Education",
    incomeLimit: "₹2.5 Lakh / year",
    priority: 1,
    criteria: [
      "Category: ST (Scheduled Tribe)",
      "Class: 11th and 12th / Post-Secondary courses",
      "Family Income: Up to ₹2.5 Lakh per annum",
      "Application Window: June 1 – October 31",
    ],
    requiredDocuments: ["Aadhaar Identity", "ST Community Certificate", "Income Certificate", "Domicile Certificate", "Academic Marksheet", "Bonafide Certificate"],
  },
  {
    id: "top-class",
    shortName: "National Scholarship (Higher Education)",
    name: "National Scholarship for Higher Education (Top Class ST)",
    description: "Full financial assistance for ST students admitted to notified premier institutes (IITs, IIMs, NITs, AIIMS, etc.).",
    benefit: "Full tuition fees + ₹3,000 monthly allowance + book grant",
    deadline: "31 October 2026",
    timeline: "June 1 – October 31",
    category: "ST",
    targetClass: "Premier institutes (IITs, IIMs, NITs, AIIMS)",
    incomeLimit: "₹6.0 Lakh / year",
    priority: 2,
    criteria: [
      "Category: ST (Scheduled Tribe)",
      "Class / Institute: Premier institutes (like IITs, IIMs, NITs, AIIMS)",
      "Family Income: Up to ₹6.0 Lakh per annum",
      "Application Window: June 1 – October 31",
    ],
    requiredDocuments: ["ST Community Certificate", "Income Certificate", "Admission Proof", "Academic Marksheet", "Bonafide Certificate"],
  },
  {
    id: "nfst",
    shortName: "National Fellowship",
    name: "National Fellowship for Higher Education of ST Students",
    description: "Fellowship support for ST students pursuing M.Phil / Ph.D. degrees with minimum 55% marks in Master's.",
    benefit: "JRF: ₹37,000/mo | SRF: ₹42,000/mo + HRA & Contingency",
    deadline: "31 October 2026",
    timeline: "June 1 – October 31",
    category: "ST",
    targetClass: "Post-Graduation/Master's (min 55% marks)",
    incomeLimit: "No limit",
    priority: 1,
    criteria: [
      "Category: ST (Scheduled Tribe)",
      "Class / Qualification: Post-Graduation/Master's Degree with a minimum of 55% marks",
      "Family Income: No limit (No ceiling)",
      "Application Window: June 1 – October 31",
    ],
    requiredDocuments: ["ST Community Certificate", "Research Admission Letter", "Master's Degree Marksheet (>=55%)", "Academic Marksheet"],
  },
  {
    id: "nos",
    shortName: "National Overseas",
    name: "National Overseas Scholarship for ST Students (NOS)",
    description: "Financial assistance for meritorious ST candidates selected for Master's, Ph.D. or Post-Doctoral studies abroad.",
    benefit: "Full international tuition fees + living allowance ($15,400/yr / £9,900/yr) + airfare",
    deadline: "Strict 30–45 days from notification",
    timeline: "Strict 30–45 days",
    category: "ST",
    targetClass: "Master's, Ph.D., or Post-Doctoral",
    incomeLimit: "₹6.0 Lakh / year",
    priority: 3,
    criteria: [
      "Category: ST (Scheduled Tribe)",
      "Class / Level: Master's, Ph.D., or Post-Doctoral",
      "Family Income: Up to ₹6.0 Lakh per annum",
      "Application Window: Strict 30–45 days",
    ],
    requiredDocuments: ["Passport", "ST Community Certificate", "Income Certificate", "Overseas Offer Letter", "Academic Marksheet"],
  },
]

const applicationPeople = [
  ["student-arun", "Arun Kumar", "ABC Engineering College"],
  ["app-priya-s", "Priya S", "Government Arts College, Salem"],
  ["app-karthik", "Karthik R", "Coimbatore Institute of Technology"],
  ["app-meena", "Meena Devi", "Central University of Jharkhand"],
  ["app-sanjay", "Sanjay Kumar", "Birsa Institute of Technology"],
  ["app-divya", "Divya M", "Madras Christian College"],
  ["app-rahul", "Rahul P", "Government Polytechnic, Ooty"],
  ["app-kavya", "Kavya N", "Presidency College Chennai"],
  ["app-vikram", "Vikram Singh", "NIT Tiruchirappalli"],
  ["app-anitha", "Anitha Lakra", "Ranchi University"],
  ["app-mohan", "Mohan Raj", "Loyola College Chennai"],
  ["app-rekha", "Rekha Kumari", "Delhi University"],
  ["app-ajay", "Ajay Hembram", "Jadavpur University"],
  ["app-nandhini", "Nandhini K", "Anna University"],
  ["app-rohit", "Rohit Munda", "Utkal University"],
  ["app-selvi", "Selvi R", "Government College Dharmapuri"],
] as const

const statusCycle: ApplicationRecord["status"][] = ["Pending", "Sanctioned", "Rejected"]

export const applications: ApplicationRecord[] = applicationPeople.map((person, index) => ({
  id: index === 0 ? "ST2026PM00124" : `ST2026PM00${125 + index}`,
  studentId: person[0],
  studentName: person[1],
  scholarshipId: "post-matric",
  college: person[2],
  appliedDate: `${String(8 + (index % 18)).padStart(2, "0")} Sep 2026`,
  academicYear: "2026–27",
  status: index === 0 ? "Institution Verification" : statusCycle[index % 3],
  expectedBenefit: "₹48,000",
  paymentStatus: index % 3 === 1 ? "Approved for payment" : "Not initiated",
  dbtStatus: index % 3 === 1 ? "Bank account verified" : "Verification pending",
  deficiency: index === 0 ? "Income Certificate needs attention" : undefined,
}))

export const otherApplications: ApplicationRecord[] = [
  {
    id: "ST2026TC00048",
    studentId: "student-priya",
    studentName: "Priya Kumar",
    scholarshipId: "top-class",
    college: "Government Tribal Residential School",
    appliedDate: "02 Sep 2026",
    academicYear: "2026–27",
    status: "Sanctioned",
    expectedBenefit: "₹72,000",
    paymentStatus: "Payment scheduled",
    dbtStatus: "Bank account verified",
  },
]

export const eligibleNotApplied = [
  ["Nila S", "B.Sc Mathematics", "Government Arts College, Ooty", "Post-Matric", "98411 22001"],
  ["Aakash M", "Class 9", "Eklavya Model School", "Pre-Matric", "98411 22002"],
  ["Deepa Lakra", "B.A Economics", "Ranchi Women’s College", "Post-Matric", "98411 22003"],
  ["Manoj H", "B.Tech Civil", "NIT Trichy", "Top Class", "98411 22004"],
  ["Sowmya R", "M.Sc Chemistry", "Bharathiar University", "Post-Matric", "98411 22005"],
  ["Rakesh Munda", "Ph.D. History", "Delhi University", "NFST", "98411 22006"],
  ["Geetha P", "Diploma Nursing", "Government Nursing College", "Post-Matric", "98411 22007"],
  ["Naveen K", "Class 10", "Tribal Welfare School", "Pre-Matric", "98411 22008"],
  ["Latha Devi", "B.Com", "Government College Salem", "Post-Matric", "98411 22009"],
  ["Suresh B", "B.E Mechanical", "Anna University", "Top Class", "98411 22010"],
  ["Amala T", "M.Phil Social Work", "University of Madras", "Post-Matric", "98411 22011"],
  ["John Ekka", "Ph.D. Education", "Central University", "NFST", "98411 22012"],
].map(([name, education, college, scholarship, phone], index) => ({
  id: `eligible-${index + 1}`,
  name,
  education,
  college,
  scholarship,
  phone,
  status: "Not Applied" as const,
}))

export const families: FamilyProfile[] = [
  { id: "family-lakshmi", parentName: "Lakshmi Devi", phone: "98760 12345", childIds: ["student-arun", "student-priya"] },
  { id: "family-sunita", parentName: "Sunita Munda", phone: "98670 45678", childIds: ["student-meena"] },
]

export const notifications: NotificationRecord[] = [
  { id: "n1", audience: "student", title: "Application moved forward", message: "Your Post-Matric application has moved to Institution Verification.", date: "Today, 10:30 AM", read: false },
  { id: "n2", audience: "student", title: "Action required", message: "Income Certificate requires attention.", date: "Yesterday", read: false },
  { id: "n3", audience: "student", title: "Application sanctioned", message: "Your scholarship application has been sanctioned.", date: "18 Sep 2026", read: true },
  { id: "n4", audience: "family", childId: "student-arun", title: "Arun’s application update", message: "Post-Matric application is under institution verification.", date: "Today", read: false },
  { id: "n5", audience: "family", childId: "student-priya", title: "Priya’s scholarship sanctioned", message: "Top Class Scholarship has been sanctioned.", date: "Yesterday", read: false },
  { id: "n6", audience: "admin", title: "Pending review", message: "42 Post-Matric applications are pending review.", date: "Today", read: false },
]

export const adminScholarshipStats = [
  { scholarshipId: "pre-matric", applications: 94, pending: 31, sanctioned: 54, rejected: 9 },
  { scholarshipId: "post-matric", applications: 128, pending: 42, sanctioned: 70, rejected: 16 },
  { scholarshipId: "top-class", applications: 62, pending: 18, sanctioned: 39, rejected: 5 },
  { scholarshipId: "nfst", applications: 28, pending: 9, sanctioned: 16, rejected: 3 },
  { scholarshipId: "nos", applications: 17, pending: 6, sanctioned: 8, rejected: 3 },
]

export const adminProfile = {
  name: "Dr. Kavitha Rao",
  department: "Tribal Welfare Department",
  role: "Scholarship Nodal Officer",
}
